### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @mturja-vf-ic-bd  with @lassoan in cc:

```
Subject: Help to merge https://github.com/mturja-vf-ic-bd/SlicerSurfaceLearner/pull/9

Md Asadullah Turja,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/mturja-vf-ic-bd/SlicerSurfaceLearner/pull/9

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
Follow-up email sent on June 19th 2024 to @mturja-vf-ic-bd with @lassoan in cc:

```
Md Asadullah Turja,

Let us know if you need anything to move forward with the integration of the referenced pull requests.

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
@allemangD Do you happen to have a way to get in touch of the maintainer ? And is this extension part of the SlicerSALT distribution ?

**Comment by allemangD** [comment]
> @allemangD Do you happen to have a way to get in touch of the maintainer ? And is this extension part of the SlicerSALT distribution ?

I only have his email. It is not in in SALT.

**Comment by jcfr** [comment]
@allemangD  

Does the email in your contact match the one reported in [their profile](https://github.com/mturja-vf-ic-bd) ?

**Comment by allemangD** [comment]
No, that's the same one I have.

**Comment by mturja-vf-ic-bd** [comment]
@jcfr Merged!

**Pull request merged**
